apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask-app
spec:
  serviceName: "flask-service"
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: your-docker-image:latest  # Replace with your actual image
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: flask-storage
          mountPath: /app
      volumes:
      - name: flask-storage
        persistentVolumeClaim:
          claimName: flask-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
